### ISSUE TITLE
Some SSZ generic bitlist tests don't follow testing format

### ISSUE THREAD

**Issue by michaelsproul** [ethereum/consensus-spec-tests#14]
The `bitlist` tests in the `ssz_generic` subdir are meant to have names of the form `bitlist_{length}_{extra}`, but there are three that don't conform to this and complicate parsing:

* `bitlist_no_delimiter_empty`
* `bitlist_no_delimiter_zero_byte`
* `bitlist_no_delimiter_zeroes`

**Comment by protolambda** [comment]
Thanks for creating an issue to track this, I will change this after interop, I am not planning for another testing release before lock-in.

**Comment by michaelsproul** [comment]
pretty sure this is stale now
