### ISSUE TITLE
v1.2.0-rc.1 tests are missing mainnet sync committee update tests

### ISSUE THREAD

**Issue by michaelsproul** [ethereum/consensus-spec-tests#29]
The tests previously located at `tests/mainnet/altair/epoch_processing/sync_committee_updates` are missing from the v1.2.0-rc.1 tarballs

**Comment by hwwhww** [comment]
Hi @michaelsproul! 

All `epoch_processing/sync_committee_updates` tests are minimal preset only. However, the test generator created the folder by default.

@ralexstokes also found it last month and we updated the test generator runner script to delete the empty folders. Next time there should be no empty folders in the tarballs.

Thanks for the report! 🙏

**Comment by michaelsproul** [comment]
Awesome, thanks, that makes sense!
